### PR TITLE
Octomap addition

### PR DESCRIPTION
**Pull request by ivrolan**
In this PR, an octomap of the 3D environment in the gazebo simulation is created. The function `create_octomap()` traverses the space in cubes of `resolution` meters. A ray is casted in X, Y and Z axis to check if there is a collision. If indeed there is a collision, the cube is added to the octomap.

Additionally, a rviz config has been added to `test/rviz` to get the same config I show in the examples below.

However, this branch parts from the #2 PR

## Tree and car world 

Screenshot from 2022-11-04 12-08-01
Screenshot from 2022-11-04 12-08-08

## Apollo world
Screenshot from 2022-11-04 12-39-27

### CODE REVIEW

**Comment by fmrico** [comment]
Hi @ivrolan 

Please, check this. The CI is failing..

**Comment by ivrolan** [comment]
Hi, I'll work on this rn. The CI wasn't running on my fork before

**Comment by ivrolan** [comment]
Let's check these new changes.

- Changed ROS version from **Galactic** to **Rolling**
- Added new dependencies to `package.xml`
- As the grid_map repo has its own `dependency_repos.repo` with the `navigation2` repo, I added it to ours

If this PR is approved, I'll add changes to the README.md

**Comment by ivrolan** [comment]
Additionally, I changed the version of the action-ros-ci to a newer version that supports `jammy` and takes into account that ros1 cannot be installed in ubuntu 22

**Comment by ivrolan** [comment]
Hi @fmrico ,

checks passed. However, check the changes made in the CI listed before:

> 
    - Changed ROS version from Galactic to Rolling
    - Added new dependencies to package.xml
    - As the grid_map repo has its own dependency_repos.repo with the navigation2 repo, I added it to ours
    - changed the version of the action-ros-ci to a newer version that supports jammy and takes into account that ros1 cannot be installed in ubuntu 22

**Comment by fmrico** [comment]
Merging!!! 🚀

**Pull request merged**
